### ISSUE TITLE
message,MW_printfの利用

### ISSUE THREAD

**Issue by elect-gombe** [wakabayashiryo/STM32F1_HAL#2]
# メッセージの作成
メッセージ表示について。今回は2種類用意されている。

- MX_printf(fmt,...)
- message(type,fmt,...)

さらにこの関数によるメッセージ転送用関数も用意されている。
- flush (void)

これらの働きの説明をする。

- MX_printf...printf。flushで過去の履歴をすべて出す。
- message...typeには種類[err,msgなど]、fmtにはメッセージ(フォーマット対応)を入れる。

messageはバッファリングされず瞬時に送信される。(現在はそうであるが、まだマスターには上がっていない。(systask)過去のものは転送されないのでユーザーが出力関数を直接叩く。)それに対してMW_printfではバッファに貯められる。flush関数で一気に転送される。

message関数とMW_printfを試しに使って出力方式の違いについて考えて欲しい。

# やること
- [x] measage関数でmessageを出力する。
- [x] MX_printfを使ってスイッチが押されていたらPushed、離されたらReleasedと表示する。

いづれも転送時間を考えて待ち時間を入れて適切な表示をすること。
@Semi11 @okapy142

**Comment by elect-gombe** [comment]
@Semi11 どの程度完了しましたか？チェックボックスにチェックを入れて進捗をあげましょう。
あともう一つブランチを作ってコードもあげましょう。

**Comment by Semi11** [comment]
メッセージ出力テスト完了しました。

**Comment by elect-gombe** [comment]
わかりました。
okapyにもよろしく。これは解決したので閉じます。
