### ISSUE TITLE
実際のコードの作成

### ISSUE THREAD

**Issue by elect-gombe** [wakabayashiryo/STM32F1_HAL#7]
#月曜日に検証するためのコード作成
#3 の続きです
- [x] ABシステムの消去
- [x] モータの回転方向を考える。MDの右左どちらかも決める。
- [x] MDのアドレスの割り振りを直す。
- [x]  左右のバランスを調節するための定義を追加(additional
 -[ ] ハードウェアの制作
@Semi11

**Comment by Semi11** [comment]
完了しました
