### ISSUE TITLE
台形制御を使う

### ISSUE THREAD

**Issue by elect-gombe** [wakabayashiryo/STM32F1_HAL#9]
#  台形制御
## 理論

  
![2016-07-16](https://cloud.githubusercontent.com/assets/13552050/16899656/cd19cec0-4c46-11e6-9fe8-13b0ce2fff8e.png)
デューティ
↑. /￣￣￣￣￣￣\
|./ ____________＿\
+------------→時間
↑立ち上がり.....↑たち下がり
ステック倒す... ステック戻す

変化量xに対に対して
-c1<(dx/dt)<c2
で表されるようにプログラムします。
cは傾きの最大値を表します

- スムーズな滑出し終わりを実現できるほかMDの負荷を減らせます。
- 時間の関わる制御について知れます。(フィードバック制御
- ギアヘッドの破損を防ぎます

## 実現方法
以下の手順で実現します。まず台形制御では以前のデータが必要です。傾きを考えるためです。
また、一定に間隔で処理をする必要があります。これは正確な傾きを実現するためです。この二つが揃った時に初めて制御できます。

処理はいたって簡単です。難しそうに見えるのは名前のせいなので。傾きに制限をかけるだけなので目標値がｖ、現在の値がxとすると速度ｙは
``` c
if(v < x){
  y = x - c1;
}
else if(v > x){
y = x + c2;
}
```
 とできそうですが、c1やｃ2の値によって収束しないおそれがあります。これは発散（発振）するおそれもあります。これは傾きが0,-c1,c2のいずれかにおいて収束する可能性が低いからです。
- 収束するようにc1,c2を定める。→収束する条件を示す。
- どのような値において収束するようにプログラムを書く。
@Semi11 @okapy142 
```
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
hoge.
```
![2016-07-17 1](https://cloud.githubusercontent.com/assets/13552050/16899794/859510aa-4c4b-11e6-8490-14652fa658ba.png)
![2016-07-17](https://cloud.githubusercontent.com/assets/13552050/16899793/85937eac-4c4b-11e6-97d4-ff0f7b0c4a11.png)

``` c
if(v < x){
  y = x - min(c1,x - v);
}
else if(v > x){
  y = x + min(c2,v - x);
}
```
苦笑

**Comment by elect-gombe** [comment]
![2016-07-17 2](https://cloud.githubusercontent.com/assets/13552050/16900080/a19498f8-4c54-11e6-8d48-0cdce1f1c413.png)

違う制御方法の特性グラフです。補足が早いのが特徴です。

**Comment by elect-gombe** [comment]
``` sh
$ cat in
1
2
3
$ ./a.out < in
1,2,3,
$ cat program.c
#include <stdio.h>
int main(void){
  int a,b,c;
  scanf("%d",&a);
  scanf("%d",&b);
  scanf("%d",&c);
  printf("%d,%d,%d,",a,b,c);
}
```

**Comment by Semi11** [comment]
完了しました
